### ISSUE TITLE
Address field does breaks for inputs from some languages

### ISSUE THREAD

**Issue by antgyf** [AY2425S1-CS2103T-T12-1/tp#143]
Currently tested to be working: Chinese, Japanese

Not working: Thai, Hebrew, Tamil

We should either change it to accept more inputs (which I think will be difficult) or change our documentation for address field. Currently, MESSAGE_CONSTRAINT for address is "Addresses can take any values, and it should not be blank".

**Comment by Jayden-Kim-NUS** [comment]
This will be in planned enhancements
