### ISSUE TITLE
[PE-D][Tester A] User guide search command example description 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#172]
Under the user guide, there was an example provided "search e Summer Fashion returns events with tags named Summer or Fashion". However, if there is an event tagged with both "Summer" and "Fashion", it will be reflected in the command output as well.

The user guide will need to include something like "...returns events with tags named Summer or Fashion or Both", to match the feature's actual output.

![Screenshot 2024-11-08 at 4.17.12 PM.png](https://raw.githubusercontent.com/M-kew/ped/main/files/6aacba05-d433-4a87-9796-4fb14ed61f7d.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: M-kew/ped#1

**Comment by Jayden-Kim-NUS** [comment]
4 lines above this in the UG there is a line that says

> * Events with tags matching at least one keyword will be returned (i.e. `OR` search).

Which should clarify any doubts the user has about how the search is done.
On top of that, the English word "or" is not exclusive by default.
This will be closed as it is a non-issue.
