### ISSUE TITLE
[PE-D][Tester C] Name of jar file is incorrect.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-1/tp#176]
The name for the jar file has not been updated throughout the user guide.

It says addressbook.jar everywhere instead of Eventory.jar.

Due to this, the instructions for quick start become incorrect and you get the error that such a jar file does not exist.

![Screenshot 2024-11-08 at 4.24.49 PM.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/bbfa452a-94fd-4cfa-939c-d2c8b8922e08.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ishan-agarwal-05/ped#1

**Comment by Jayden-Kim-NUS** [comment]
Duplicate
