### ISSUE TITLE
[PE-D][Tester C] Multiple Phone numbers and emails not allowed for contacts

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-1/tp#189]
Multiple Phone numbers or multiple emails not allowed for contacts. It might be helpful to save more than 1 email of some person.

![Screenshot 2024-11-08 at 4.50.01 PM.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/ee97e352-79ba-4947-a0aa-007862e6ab85.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ishan-agarwal-05/ped#3

**Comment by Jayden-Kim-NUS** [comment]
Thanks for the suggestion, this will be included in planned enhancements
