### ISSUE TITLE
[PE-D][Tester E] Error messages can be more meaningful for schedule feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#217]
Input: `schedule 2024-01`

Expected: error message for invalid date provided
Actual:
![image.png](https://raw.githubusercontent.com/zi-yii/ped/main/files/02b696ec-d37d-45c0-8ac4-af65ec2c56cd.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: zi-yii/ped#13

**Comment by Jayden-Kim-NUS** [comment]
Thanks for the suggestion, this will be included in planned-enhancements
