### ISSUE TITLE
[PE-D][Tester C] No way to search for all contacts or events that don't have tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#228]
I couldn't find a way to search for the contacts or events that don't have any tags. Users might want to be able to do that to then more easily add tags or something like that
![Screenshot 2024-11-08 at 7.54.56 PM.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/4d689e34-5a99-49b1-87f1-f5b04e270a7a.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ishan-agarwal-05/ped#11

**Comment by antgyf** [comment]
Shall we just add a comment for this in the UG? I don't think it makes sense to change the command...

**Comment by Jayden-Kim-NUS** [comment]
Thank you for the suggestion, in my opinion this feature is barely useful. Consider closing.
