### ISSUE TITLE
[PE-D][Tester C] Event name case sensitive for link command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#231]
User might expect the event name to be case insensitive to use in link command.
eg:

![Screenshot 2024-11-08 at 8.07.43 PM.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/b3226ce3-6c46-4f2a-a8c1-fe6284fa349c.png)

User might expect this to work to be linked with test 1

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ishan-agarwal-05/ped#14

**Comment by Jayden-Kim-NUS** [comment]
Event name in link command is case sensitive as 2 different events with different cases can exist at the same time eg `Sentosa` and `sentosa`. This is intended.
This will be closed as it is not a `type.FunctionalityBug`
