### ISSUE TITLE
[PE-D][Tester C] Table of content looks too plain

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-1/tp#232]
Table of content looks too dull and plain. Also the size is weirdly small. The fint size is inconsistent between DG and UG  ToC

![image.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/b386f196-202d-4c11-8dcd-051c1a40ba98.png)

![image.png](https://raw.githubusercontent.com/ishan-agarwal-05/ped/main/files/87120f2b-8908-4a69-94ed-b9b60fc54655.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ishan-agarwal-05/ped#15

**Comment by Jayden-Kim-NUS** [comment]
Thank you for the suggestions for improvements.
This will be close as it is a non-issue and a issue of personal preference.
